apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-rancher
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: nginx
        image: manish8757/rancher:a7655d5e86991cdd6dfef572304bfbb95ee14cd7
        ports:
        - containerPort: 8080
